# Logfile Details
log:
    file: cam_slurper.log
    format: '[%(asctime)s] [%(levelname)s] - %(message)s'
    dateformat: '%Y-%m-%d %H:%M:%S'

# Dynect Credentials; read-only required
camera:
    name: ipad2
    hostname: http://blue.local
    store_path: /Volumes/Surveillance/videos/

# how often to rotate the files (in seconds) (900 is 15 minutes)
rotate_duration: 900

# maximum size (sum of files) in store_path, in MB. oldest files will be 
# deleted is size exceeds this value.
max_dir_size: 50000